        "dsw": {
            "account_number_column": "CndbAccountNumber",
            "add_columns": {
                "Source": "DSW",
                "StagingTags": null,
                "UpdatedBy": "",
                "UpdatedOn": "AtomBridge"
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "CntryCode",
                "SoldToCustNum",
                "CndbAccountNumber",
                "SapDistribtnChnlCode",
                "SapDistribtnChnlCodeDscr",
                "AgrmtTypeCodeDscr",
                "SaasTotCmmtmtVal",
                "SaasAnlCmmtmtVal",
                "SapMatlGrp5CondCode",
                "PartNum",
                "PartDscrFull",
                "SapMatlTypeCode",
                "SapMatlTypeCodeDscr",
                "CvrageTerm",
                "PartQty",
                "CuUomCode",
                "CuDscr",
                "CurrencyCode",
                "FirmOrdDate",
                "StartDate",
                "EndDate",
                "RenwlStartDate",
                "RenwlEndDate",
                "SbscrptnStartDate",
                "SbscrptnEndDate",
                "ServsStartDate",
                "SaasTermntdDate",
                "RselOrdDate",
                "OrdgMethodCode",
                "OrdgMethodCodeDscr",
                "SoldToSapCntId",
                "PayerCustNum",
                "PayerSapCntId",
                "SbscrptnSaasTermntdDate",
                "TouAmenddFlag",
                "CmrCustNum",
                "CmrSysLocCode",
                "HostedCustCode",
                "IsoCntryCode",
                "MppCustNum",
                "City",
                "AdrIntrnl",
                "SapMatlGrp",
                "SaasOnDmndFlag",
                "SapCtrctVarintCode",
                "ShipToCustNum",
                "EndUserCustNum",
                "EndUserCustNameFull",
                "CurrStartDate",
                "CurrEndDate",
                "OrignlSalesOrdRefNum",
                "BackDatedStartDate",
                "Unnamed53",
                "Unnamed54"
            ],
            "file_name_starts_with": "DSW_ENTITLEMENT_DATA",
            "file_type": [
                "csv"
            ],
            "folder_name": "EN_DSW_DATA",
            "rename_columns": {
                "ADR_INTRNL": "AdrIntrnl",
                "AGRMT_TYPE_CODE_DSCR": "AgrmtTypeCodeDscr",
                "BACK_DATED_START_DATE": "BackDatedStartDate",
                "CITY": "City",
                "CMR_CUST_NUM": "CmrCustNum",
                "CMR_SYS_LOC_CODE": "CmrSysLocCode",
                "CNDB ACCOUNT NUMBER": "CndbAccountNumber",
                "CNTRY_CODE": "CntryCode",
                "CURRNCY_CODE": "CurrencyCode",
                "CURR_END_DATE": "CurrEndDate",
                "CURR_START_DATE": "CurrStartDate",
                "CU_DSCR": "CuDscr",
                "CU_UOM_CODE": "CuUomCode",
                "CVRAGE_TERM": "CvrageTerm",
                "END_DATE": "EndDate",
                "END_USER_CUST_NAME_FULL": "EndUserCustNameFull",
                "END_USER_CUST_NUM": "EndUserCustNum",
                "FIRM_ORD_DATE": "FirmOrdDate",
                "HOSTED_CUST_CODE": "HostedCustCode",
                "ISO_CNTRY_CODE": "IsoCntryCode",
                "MPP_CUST_NUM": "MppCustNum",
                "ORDG_METHOD_CODE": "OrdgMethodCode",
                "ORDG_METHOD_CODE_DSCR": "OrdgMethodCodeDscr",
                "ORIGNL_SALES_ORD_REF_NUM": "OrignlSalesOrdRefNum",
                "PART_DSCR_FULL": "PartDscrFull",
                "PART_NUM": "PartNum",
                "PART_QTY": "PartQty",
                "PAYER_CUST_NUM": "PayerCustNum",
                "PAYER_SAP_CNT_ID": "PayerSapCntId",
                "RENWL_END_DATE": "RenwlEndDate",
                "RENWL_START_DATE": "RenwlStartDate",
                "RSEL_ORD_DATE": "RselOrdDate",
                "SAAS_ANL_CMMTMT_VAL": "SaasAnlCmmtmtVal",
                "SAAS_ON_DMND_FLAG": "SaasOnDmndFlag",
                "SAAS_TERMNTD_DATE": "SaasTermntdDate",
                "SAAS_TOT_CMMTMT_VAL": "SaasTotCmmtmtVal",
                "SAP_CTRCT_VARIANT_CODE": "SapCtrctVarintCode",
                "SAP_DISTRIBTN_CHNL_CODE": "SapDistribtnChnlCode",
                "SAP_DISTRIBTN_CHNL_CODE_DSCR": "SapDistribtnChnlCodeDscr",
                "SAP_MATL_GRP": "SapMatlGrp",
                "SAP_MATL_GRP_5_COND_CODE": "SapMatlGrp5CondCode",
                "SAP_MATL_TYPE_CODE": "SapMatlTypeCode",
                "SAP_MATL_TYPE_CODE_DSCR": "SapMatlTypeCodeDscr",
                "SBSCRPTN_END_DATE": "SbscrptnEndDate",
                "SBSCRPTN_SAAS_TERMNTD_DATE": "SbscrptnSaasTermntdDate",
                "SBSCRPTN_START_DATE": "SbscrptnStartDate",
                "SERVS_START_DATE": "ServsStartDate",
                "SHIP_TO_CUST_NUM": "ShipToCustNum",
                "SOLD_TO_CUST_NUM": "SoldToCustNum",
                "SOLD_TO_SAP_CNT_ID": "SoldToSapCntId",
                "START_DATE": "StartDate",
                "TOU_AMENDD_FLAG": "TouAmenddFlag",
                "Unnamed: 53": "Unnamed53",
                "Unnamed: 54": "Unnamed54"
            },
            "staging_table_name": "bridge.tbl_ibm_dsw_staging"
        },
        "esw": {
            "account_number_column": "AccountNumber",
            "add_columns": {
                "Source": "ESW",
                "StagingTags": null,
                "UpdatedBy": "",
                "UpdatedOn": "AtomBridge"
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "AccountNumber",
                "Market",
                "SalesDocOrderNo",
                "SalesDocItemNo",
                "MaterialNo",
                "MaterialDescr",
                "CustnoSoldTo",
                "CustNameSoldTo",
                "CntryCdLgcySoldTo",
                "CustnoLgcySoldTo",
                "CustnoBillTo",
                "CustNameBillTo",
                "CntryCdLgcyBillTo",
                "CustnoLgcyBillTo",
                "CustnoInstallAt",
                "CntryCdLgcyInstallAt",
                "CustnoLgcyInstallAt",
                "CustnoPayer",
                "CntryCdLgcyPayer",
                "CustnoLgcyPayer",
                "DesgnMachNo",
                "ProductDivision",
                "OrderEntryDate",
                "SerialNo",
                "Equipement",
                "StartLast"
            ],
            "file_name_starts_with": "ESW_ENTITLEMENT_DATA",
            "file_type": [
                "csv"
            ],
            "folder_name": "EN_ESW_DATA",
            "rename_columns": {
                "ACCOUNT_NUMBER": "AccountNumber",
                "CNTRY_CD_LGCY_BILL_TO": "CntryCdLgcyBillTo",
                "CNTRY_CD_LGCY_INSTALL_AT": "CntryCdLgcyInstallAt",
                "CNTRY_CD_LGCY_PAYER": "CntryCdLgcyPayer",
                "CNTRY_CD_LGCY_SOLD_TO": "CntryCdLgcySoldTo",
                "CUSTNO_BILL_TO": "CustnoBillTo",
                "CUSTNO_INSTALL_AT": "CustnoInstallAt",
                "CUSTNO_LGCY_BILL_TO": "CustnoLgcyBillTo",
                "CUSTNO_LGCY_INSTALL_AT": "CustnoLgcyInstallAt",
                "CUSTNO_LGCY_PAYER": "CustnoLgcyPayer",
                "CUSTNO_LGCY_SOLD_TO": "CustnoLgcySoldTo",
                "CUSTNO_PAYER": "CustnoPayer",
                "CUSTNO_SOLD_TO": "CustnoSoldTo",
                "CUST_NAME_BILL_TO": "CustNameBillTo",
                "CUST_NAME_SOLD_TO": "CustNameSoldTo",
                "DESGN_MACH_NO": "DesgnMachNo",
                "EQUIPEMENT": "Equipement",
                "MATERIAL_DESCRIPTION": "MaterialDescr",
                "MATERIAL_NO": "MaterialNo",
                "Market": "Market",
                "ORDER_ENTRY_DATE": "OrderEntryDate",
                "PRODUCT_DIVISION": "ProductDivision",
                "SALES_DOC_ITEM_NO": "SalesDocItemNo",
                "SALES_DOC_ORDER_NO": "SalesDocOrderNo",
                "SERIAL": "SerialNo",
                "STAT LAST": "StartLast"
            },
            "staging_table_name": "bridge.tbl_ibm_entitlements_esw"
        },
        "tadz": {
            "account_number_column": "",
            "add_columns": {
                "Source": "Tadz",
                "StagingTags": null,
                "UpdatedBy": "AtomBridge",
                "UpdatedOn": ""
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "TsId",
                "SId",
                "SmfId",
                "SysPlex",
                "HwType",
                "HwModel",
                "HwPlant",
                "HwName",
                "LparName",
                "NodeLastUpdate",
                "CpuSn"
            ],
            "file_name_starts_with": "LPAR",
            "file_type": [
                "csv"
            ],
            "folder_name": "SC_MF_TEDz_DATA",
            "rename_columns": {
                "CPU_SN": "CpuSn",
                "HW_MODEL": "HwModel",
                "HW_NAME": "HwName",
                "HW_PLANT": "HwPlant",
                "HW_TYPE": "HwType",
                "LPAR_NAME": "LparName",
                "NODE_LAST_UPDATE": "NodeLastUpdate",
                "SID": "SId",
                "SMFID": "SmfId",
                "SYSPLEX": "SysPlex",
                "TSID": "TsId"
            },
            "staging_table_name": "bridge.tbl_ibm_tadz_lpar_staging"
        },


###############################################################################
        "dsw":{
            "account_number_column": "AccountNumber",
            "add_columns": {
                "Source": "DSW",
                "StagingTags": null,
                "UpdatedBy": "",
                "UpdatedOn": "AtomBridge"
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "AccountNumber",
                "UniqueId",
                "SapSalesOrgCode",
                "CntryCode",
                "SoldToCustNum",
                "MasterFileComment",
                "SapSalesOrdNum",
                "LineItemSeqNum",
                "SapMatlGrp5CondCode",
                "PartNum",
                "PartDscrFull",
                "SapMatlTypeCode",
                "SapMatlTypeCodeDscr",
                "PartQty",
                "CuUomCode",
                "CuDscr",
                "StartDate",
                "EndDate",
                "ConfigrtnId",
                "QuoteNum",
                "QuoteLineItemSeqNum",
                "BillToPurchOrdNum",
                "RselOrdDate",
                "OrdgMethodCode",
                "OrdgMethodCodeDscr",
                "SoldToSapCntId",
                "PayerCustNum",
                "PayerSapCntId",
                "BillToCustNum",
                "RselCustNum",
                "ShipToCustNum",
                "SapCtrctNum",
                "CmrCustNum",
                "CmrSysLocCode"
            ],
            "file_name_starts_with": "DSW_ENTITLEMENT_DATA",
            "file_type": [
                "csv"
            ],
            "folder_name": "EN_DSW_DATA",
            "rename_columns": {
                "ACCOUNT_NUMBER": "AccountNumber",
                "UNIQUE_ID": "UniqueId",
                "SAP_SALES_ORG_CODE": "SapSalesOrgCode",
                "CNTRY_CODE": "CntryCode",
                "SOLD_TO_CUST_NUM": "SoldToCustNum",
                "Master File Comment": "MasterFileComment",
                "SAP_SALES_ORD_NUM": "SapSalesOrdNum",
                "LINE_ITEM_SEQ_NUM": "LineItemSeqNum",
                "SAP_MATL_GRP_5_COND_CODE": "SapMatlGrp5CondCode",
                "PART_NUM": "PartNum",
                "PART_DSCR_FULL": "PartDscrFull",
                "SAP_MATL_TYPE_CODE": "SapMatlTypeCode",
                "SAP_MATL_TYPE_CODE_DSCR": "SapMatlTypeCodeDscr",
                "PART_QTY": "PartQty",
                "CU_UOM_CODE": "CuUomCode",
                "CU_DSCR": "CuDscr",
                "START_DATE": "StartDate",
                "END_DATE": "EndDate",
                "CONFIGRTN_ID": "ConfigrtnId",
                "QUOTE_NUM": "QuoteNum",
                "QUOTE_LINE_ITEM_SEQ_NUM": "QuoteLineItemSeqNum",
                "BILL_TO_PURCH_ORD_NUM": "BillToPurchOrdNum",
                "RSEL_ORD_DATE": "RselOrdDate",
                "ORDG_METHOD_CODE": "OrdgMethodCode",
                "ORDG_METHOD_CODE_DSCR": "OrdgMethodCodeDscr",
                "SOLD_TO_SAP_CNT_ID": "SoldToSapCntId",
                "PAYER_CUST_NUM": "PayerCustNum",
                "PAYER_SAP_CNT_ID": "PayerSapCntId",
                "BILL_TO_CUST_NUM": "BillToCustNum",
                "RSEL_CUST_NUM": "RselCustNum",
                "SHIP_TO_CUST_NUM": "ShipToCustNum",
                "SAP_CTRCT_NUM": "SapCtrctNum",
                "CMR_CUST_NUM": "CmrCustNum",
                "CMR_SYS_LOC_CODE": "CmrSysLocCode",
            },
            "staging_table_name": "bridge.tbl_ibm_dsw_staging"
        },
        "esw":{
            "account_number_column": "CndbId",
            "add_columns": {
                "Source": "ESW",
                "StagingTags": null,
                "UpdatedBy": "",
                "UpdatedOn": "AtomBridge"
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "Market",
                "CountryCode",
                "GeographyName",
                "SapOrderNo",
                "ItemNo",
                "Swo",
                "SwoDescription",
                "SapCustno",
                "Country",
                "SoldToCustno",
                "SapBilltoCustno",
                "CmrBilltoCustno",
                "SapInstCustno",
                "CmrInstCustno",
                "SapShiptoCustno",
                "CmrShiptoCustno",
                "DesigMachine",
                "ProdDivCode",
                "OrderCreateDate",
                "SerialNo",
                "EquipmentNo",
                "IwIbaseStatus",
                "ValueMetricDescr",
                "LicenseType",
                "OrderType",
                "ChargeOption",
                "ChgValueInteger",
                "LicEffDate",
                "RemovalDate",
                "SwoDescrUp",
                "EeDescrUp",
                "EevmDescrUp",
                "CidDescrUp",
                "CndbId"
            ],
            "file_name_starts_with": "ESW_ENTITLEMENT_DATA",
            "file_type": [
                "csv"
            ],
            "folder_name": "EN_ESW_DATA",
            "rename_columns": {
                "MARKET": "Market",
                "COUNTRY_CODE": "CountryCode",
                "GEOGRAPHY_NAME": "GeographyName",
                "SAP_ORDER_NO": "SapOrderNo",
                "ITEM_NO": "ItemNo",
                "SWO": "Swo",
                "SWO_DESCRIPTION": "SwoDescription",
                "SAP_CUSTNO": "SapCustno",
                "COUNTRY": "Country",
                "SOLD_TO_CUSTNO": "SoldToCustno",
                "SAP_BILLTO_CUSTNO": "SapBilltoCustno",
                "CMR_BILLTO_CUSTNO": "CmrBilltoCustno",
                "SAP_INST_CUSTNO": "SapInstCustno",
                "CMR_INST_CUSTNO": "CmrInstCustno",
                "SAP_SHIPTO_CUSTNO": "SapShiptoCustno",
                "CMR_SHIPTO_CUSTNO": "CmrShiptoCustno",
                "DESIG_MACHINE": "DesigMachine",
                "PROD_DIV_CODE": "ProdDivCode",
                "ORDER_CREATE_DATE": "OrderCreateDate",
                "SERIAL_NO": "SerialNo",
                "EQUIPMENT_NO": "EquipmentNo",
                "IW_IBASE_STATUS": "IwIbaseStatus",
                "VALUE_METRIC_DESCR": "ValueMetricDescr",
                "LICENSE_TYPE": "LicenseType",
                "ORDER_TYPE": "OrderType",
                "CHARGE_OPTION": "ChargeOption",
                "CHG_VALUE_INTEGER": "ChgValueInteger",
                "LIC_EFF_DATE": "LicEffDate",
                "REMOVAL_DATE": "RemovalDate",
                "SWO_DESCR_UP": "SwoDescrUp",
                "EE_DESCR_UP": "EeDescrUp",
                "EEVM_DESCR_UP": "EevmDescrUp",
                "CID_DESCR_UP": "CidDescrUp",
                "CNDB_ID": "CndbId"
            },
            "staging_table_name": "bridge.tbl_ibm_entitlements_esw"
        },
        "tadz":{
            "account_number_column": "CndbId",
            "add_columns": {
                "Source": "Tadz",
                "StagingTags": null,
                "UpdatedBy": "AtomBridge",
                "UpdatedOn": ""
            },
            "column_order": [
                "UpdatedOn",
                "UpdatedBy",
                "Source",
                "StagingTags",
                "CndbId",
                "Vendor",
                "Product",
                "VersionTitle",
                "Version",
                "Repository",
                "Pid",
                "Sspid",
                "Feature",
                "Eid",
                "HwSerial",
                "HwModel",
                "Osname",
                "MachineType",
                "Techimgid",
                "Mlc",
                "Ipla",
                "Subcapacity",
                "Annotation",
                "DiscoveryInstalled",
                "DiscoveryUninstalled",
                "SystemsInstalled",
                "FirstUsed",
                "LastUsed",
                "ExpectedInstalled",
                "ExpectedLastUsed",
                "UserCnt",
                "AccountCnt",
                "EventCnt",
                "ScrtMsu",
                "SystemsUsed",
                "MachinesUsed",
                "CpuMsu",
                "CpuIbmLspMips",
                "CpugGartnerMips",
                "Sysplex",
                "LparName",
            ],
            "file_name_starts_with": "LPAR",
            "file_type": [
                "csv"
            ],
            "folder_name": "SC_MF_TEDz_DATA",
            "rename_columns": {
                "CNDB_ID": "CndbId",
                "VENDOR": "Vendor",
                "PRODUCT": "Product",
                "VERSION_TITLE": "VersionTitle",
                "VERSION": "Version",
                "REPOSITORY": "Repository",
                "PID": "Pid",
                "SSPID": "Sspid",
                "FEATURE": "Feature",
                "EID": "Eid",
                "HW_SERIAL": "HwSerial",
                "HW_MODEL": "HwModel",
                "OSNAME": "Osname",
                "MACHINE_TYPE": "MachineType",
                "TECHIMGID": "Techimgid",
                "MLC": "Mlc",
                "IPLA": "Ipla",
                "SUBCAPACITY": "Subcapacity",
                "ANNOTATION": "Annotation",
                "DISCOVERY_INSTALLED": "DiscoveryInstalled",
                "DISCOVERY_UNINSTALLED": "DiscoveryUninstalled",
                "SYSTEMS_INSTALLED": "SystemsInstalled",
                "FIRST_USED": "FirstUsed",
                "LAST_USED": "LastUsed",
                "EXPECTED_INSTALLED": "ExpectedInstalled",
                "EXPECTED_LAST_USED": "ExpectedLastUsed",
                "USER_CNT": "UserCnt",
                "ACCOUNT_CNT": "AccountCnt",
                "EVENT_CNT": "EventCnt",
                "SCRT_MSU": "ScrtMsu",
                "SYSTEMS_USED": "SystemsUsed",
                "MACHINES_USED": "MachinesUsed",
                "CPU_MSU": "CpuMsu",
                "CPU_IBM_LSP_MIPS": "CpuIbmLspMips",
                "CPU_GARTNER_MIPS": "CpugGartnerMips",
                "SYSPLEX": "Sysplex",
                "LPAR_NAME": "LparName"
            },
            "staging_table_name": "bridge.tbl_ibm_tadz_lpar_staging"
        },

#####################################################################

CREATE TABLE bridge.tbl_ibm_entitlements_esw
(
    "UpdatedOn" timestamp without time zone NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "Source" text COLLATE pg_catalog."default",
    "StagingTags" jsonb,
    "AccountNumber" text,
    "Market" text,
    "SalesDocOrderNo" text,
    "SalesDocItemNo" text,
    "MaterialNo" text,
    "MaterialDescr" text,
    "CustnoSoldTo" text,
    "CustNameSoldTo" text,
    "CntryCdLgcySoldTo" text,
    "CustnoLgcySoldTo" text,
    "CustnoBillTo" text,
    "CustNameBillTo" text,
    "CntryCdLgcyBillTo" text,
    "CustnoLgcyBillTo" text,
    "CustnoInstallAt" text,
    "CntryCdLgcyInstallAt" text,
    "CustnoLgcyInstallAt" text,
    "CustnoPayer" text,
    "CntryCdLgcyPayer" text,
    "CustnoLgcyPayer" text,
    "DesgnMachNo" text,
    "ProductDivision" text,
    "OrderEntryDate" text,
    "SerialNo" text,
    "Equipement" text,
    "StartLast" text
)


CREATE TABLE bridge.tbl_ibm_entitlements_esw
(
    "UpdatedOn" timestamp without time zone NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "Source" text COLLATE pg_catalog."default",
    "StagingTags" jsonb,
    "Market" text,
    "CountryCode" text,
    "GeographyName" text,
    "SapOrderNo" text,
    "ItemNo" text,
    "Swo" text,
    "SwoDescription" text,
    "SapCustno" text,
    "Country" text,
    "SoldToCustno" text,
    "SapBilltoCustno" text,
    "CmrBilltoCustno" text,
    "SapInstCustno" text,
    "CmrInstCustno" text,
    "SapShiptoCustno" text,
    "CmrShiptoCustno" text,
    "DesigMachine" text,
    "ProdDivCode" text,
    "OrderCreateDate" text,
    "SerialNo" text,
    "EquipmentNo" text,
    "IwIbaseStatus" text,
    "ValueMetricDescr" text,
    "LicenseType" text,
    "OrderType" text,
    "ChargeOption" text,
    "ChgValueInteger" text,
    "LicEffDate" text,
    "RemovalDate" text,
    "SwoDescrUp" text,
    "EeDescrUp" text,
    "EevmDescrUp" text,
    "CidDescrUp" text,
    "CndbId" text
)


CREATE TABLE bridge.tbl_ibm_entitlements_dsw
(
    "UpdatedOn" timestamp without time zone NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "Source" text COLLATE pg_catalog."default",
    "StagingTags" jsonb,
    "AccountNumber" text,
    "UniqueId" text,
    "SapSalesOrgCode" text,
    "CntryCode" text,
    "SoldToCustNum" text,
    "MasterFileComment" text,
    "SapSalesOrdNum" text,
    "LineItemSeqNum" text,
    "SapMatlGrp5CondCode" text,
    "PartNum" text,
    "PartDscrFull" text,
    "SapMatlTypeCode" text,
    "SapMatlTypeCodeDscr" text,
    "PartQty" text,
    "CuUomCode" text,
    "CuDscr" text,
    "StartDate" text,
    "EndDate" text,
    "ConfigrtnId" text,
    "QuoteNum" text,
    "QuoteLineItemSeqNum" text,
    "BillToPurchOrdNum" text,
    "RselOrdDate" text,
    "OrdgMethodCode" text,
    "OrdgMethodCodeDscr" text,
    "SoldToSapCntId" text,
    "PayerCustNum" text,
    "PayerSapCntId" text,
    "BillToCustNum" text,
    "RselCustNum" text,
    "ShipToCustNum" text,
    "SapCtrctNum" text,
    "CmrCustNum" text,
    "CmrSysLocCode" text
)


CREATE TABLE bridge.tbl_ibm_tadz_lpar_staging_d
(
    "UpdatedOn" timestamp without time zone NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "Source" text COLLATE pg_catalog."default",
    "StagingTags" jsonb,
    "CndbId" text,
    "Vendor" text,
    "Product" text,
    "VersionTitle" text,
    "Version" text,
    "Repository" text,
    "Pid" text,
    "Sspid" text,
    "Feature" text,
    "Eid" text,
    "HwSerial" text,
    "HwModel" text,
    "Osname" text,
    "MachineType" text,
    "Techimgid" text,
    "Mlc" text,
    "Ipla" text,
    "Subcapacity" text,
    "Annotation" text,
    "DiscoveryInstalled" text,
    "DiscoveryUninstalled" text,
    "SystemsInstalled" text,
    "FirstUsed" text,
    "LastUsed" text,
    "ExpectedInstalled" text,
    "ExpectedLastUsed" text,
    "UserCnt" text,
    "AccountCnt" text,
    "EventCnt" text,
    "ScrtMsu" text,
    "SystemsUsed" text,
    "MachinesUsed" text,
    "CpuMsu" text,
    "CpuIbmLspMips" text,
    "CpugGartnerMips" text,
    "Sysplex" text,
    "LparName" text
)


###############################################################




    remotes/origin/latest_bridge_and_transformation_engine


    "UpdatedOn" timestamp without time zone NOT NULL,
    "UpdatedBy" text COLLATE pg_catalog."default",
    "SwcmTags" jsonb,
    "Source" text COLLATE pg_catalog."default",
    "LicenseId" text COLLATE pg_catalog."default",
    "ContractId" text COLLATE pg_catalog."default",
    "AssignedToMaintenance" text COLLATE pg_catalog."default",
    "AssignedToContract" text COLLATE pg_catalog."default",
    "ContractNumber" text COLLATE pg_catalog."default",
    "ContractName" text COLLATE pg_catalog."default",
    "ContractOwner" text COLLATE pg_catalog."default",
    "ContractStartDate" text COLLATE pg_catalog."default",
    "ContractEndDate" text COLLATE pg_catalog."default",
    "LicenseOrderCountryCode" text COLLATE pg_catalog."default",
    "CountryCodeDesc" text COLLATE pg_catalog."default",
    "CustomerName" text COLLATE pg_catalog."default",
    "CustomerNumber" text COLLATE pg_catalog."default",
    "LicenseName" text COLLATE pg_catalog."default",
    "SwProductName" text COLLATE pg_catalog."default",
    "LicenseVersionNumberVer" text COLLATE pg_catalog."default",
    "LicenseVersionNumberRel" text COLLATE pg_catalog."default",
    "LicenseVersionNumMod" text COLLATE pg_catalog."default",
    "SwManufactName" text COLLATE pg_catalog."default",
    "LicenseSherlokSkuNumber" text COLLATE pg_catalog."default",
    "LicenseSherlokSkuName" text COLLATE pg_catalog."default",
    "LicenseSwVersUpgrade" text COLLATE pg_catalog."default",
    "LicenseOwnedByIbm" text COLLATE pg_catalog."default",
    "LicenseSysplexPricing" text COLLATE pg_catalog."default",
    "SupplierName" text COLLATE pg_catalog."default",
    "LicenseTypeCode" text COLLATE pg_catalog."default",
    "LicenseTypeDesc" text COLLATE pg_catalog."default",
    "CapTypeDesc" text COLLATE pg_catalog."default",
    "LicenseCost" text COLLATE pg_catalog."default",
    "LicenseCostCurrCode" text COLLATE pg_catalog."default",
    "CostTypeDesc" text COLLATE pg_catalog."default",
    "LicensePoolUsable" text COLLATE pg_catalog."default",
    "LicenseQuantity" text COLLATE pg_catalog."default",
    "LicenseSkuCapacity" text COLLATE pg_catalog."default",
    "LicenseTotalEntitledCapacity" text COLLATE pg_catalog."default",
    "LicensePerpetual" text COLLATE pg_catalog."default",
    "LicenseCreated" text COLLATE pg_catalog."default",
    "LicenseStartDate" text COLLATE pg_catalog."default",
    "LicenseEndDate" text COLLATE pg_catalog."default",
    "LicenseRestrictedUse" text COLLATE pg_catalog."default",
    "LicenseReusable" text COLLATE pg_catalog."default",
    "LicenseSerialNumber" text COLLATE pg_catalog."default",
    "LicenseComment" text COLLATE pg_catalog."default",
    "LicenseStatusCode" text COLLATE pg_catalog."default",
    "LicenseStatusDesc" text COLLATE pg_catalog."default",
    "LicenseIbmContrRef" text COLLATE pg_catalog."default",
    "LicenseDonglePhysKey" text COLLATE pg_catalog."default",
    "LicensePurOrderNumber" text COLLATE pg_catalog."default",
    "LicensePurOrderDate" text COLLATE pg_catalog."default",
    "LicenseRestriction" text COLLATE pg_catalog."default",
    "LicenseSherlokSkuNumber1" text COLLATE pg_catalog."default",
    "OSTypeCode" text COLLATE pg_catalog."default",
    "OSTypeDesc" text COLLATE pg_catalog."default",
    "MinorCode" text COLLATE pg_catalog."default",
    "MinorCodeDesc" text COLLATE pg_catalog."default",
    "UserDataField1" text COLLATE pg_catalog."default",
    "UserDataField2" text COLLATE pg_catalog."default",
    "UserDataField3" text COLLATE pg_catalog."default",
    "UserDataField4" text COLLATE pg_catalog."default",
    "UserDataField5" text COLLATE pg_catalog."default",
    "UserDataField6" text COLLATE pg_catalog."default",
    "PlatformDesc" text COLLATE pg_catalog."default",
    "LicenseAgreeType" text COLLATE pg_catalog."default"


TABLESPACE pg_default;

ALTER TABLE bridge.tbl_ibm_swcm_license_staging
    OWNER to postgres;

    "CustomerName", text COLLATE pg_catalog."default",------
    "CostTypeDesc", text COLLATE pg_catalog."default",  --------
    "LicenseSherlokSkuNumber1", text COLLATE pg_catalog."default", ----

    CREATE TABLE bridge.tbl_ibm_swcm_license_staging
( 
    "LicenseId", text COLLATE pg_catalog."default",
    "LicenseOrderCountryCode", text COLLATE pg_catalog."default",
    "CountryCodeDesc", text COLLATE pg_catalog."default",
    "CustomerNumber", text COLLATE pg_catalog."default",
    "LicenseName", text COLLATE pg_catalog."default",
    "SwProductName", text COLLATE pg_catalog."default",
    "LicenseVersionNumberVer", text COLLATE pg_catalog."default",
    "LicenseVersionNumberRel", text COLLATE pg_catalog."default",
    "LicenseVersionNumMod", text COLLATE pg_catalog."default",
    "SwManufactName", text COLLATE pg_catalog."default",
    "LicenseSherlokSkuNumber", text COLLATE pg_catalog."default",
    "LicenseSherlokSkuName", text COLLATE pg_catalog."default",
    "LicenseSwVersUpgrade", text COLLATE pg_catalog."default",
    "LicenseOwnedByIbm", text COLLATE pg_catalog."default",
    "LicenseSysplexPricing", text COLLATE pg_catalog."default",
    "SupplierName", text COLLATE pg_catalog."default",
    "LicenseTypeCode", text COLLATE pg_catalog."default",
    "LicenseTypeDesc", text COLLATE pg_catalog."default",
    "CapTypeDesc", text COLLATE pg_catalog."default",
    "LicenseCost", text COLLATE pg_catalog."default",
    "LicenseCostCurrCode", text COLLATE pg_catalog."default",
    "LicensePoolUsable", text COLLATE pg_catalog."default",
    "LicenseQuantity", text COLLATE pg_catalog."default",
    "LicenseSkuCapacity", text COLLATE pg_catalog."default",
    "LicenseTotalEntitledCapacity", text COLLATE pg_catalog."default",
    "LicensePerpetual", text COLLATE pg_catalog."default",
    "LicenseCreated", text COLLATE pg_catalog."default",
    "LicenseStartDate", text COLLATE pg_catalog."default",
    "LicenseEndDate", text COLLATE pg_catalog."default",
    "LicenseRestrictedUse", text COLLATE pg_catalog."default",
    "LicenseReusable", text COLLATE pg_catalog."default",
    "LicenseSerialNumber", text COLLATE pg_catalog."default",
    "LicenseComment", text COLLATE pg_catalog."default",
    "LicenseStatusCode", text COLLATE pg_catalog."default",
    "LicenseStatusDesc", text COLLATE pg_catalog."default",
    "LicenseIbmContrRef", text COLLATE pg_catalog."default",
    "LicenseDonglePhysKey", text COLLATE pg_catalog."default",
    "LicensePurOrderNumber", text COLLATE pg_catalog."default",
    "LicensePurOrderDate", text COLLATE pg_catalog."default",
    "LicenseRestriction", text COLLATE pg_catalog."default",
    "OSTypeCode", text COLLATE pg_catalog."default",
    "OSTypeDesc", text COLLATE pg_catalog."default",
    "MinorCode", text COLLATE pg_catalog."default",
    "MinorCodeDesc", text COLLATE pg_catalog."default",
    "UserDataField1", text COLLATE pg_catalog."default",
    "UserDataField2", text COLLATE pg_catalog."default",
    "UserDataField3", text COLLATE pg_catalog."default",
    "UserDataField4", text COLLATE pg_catalog."default",
    "UserDataField5", text COLLATE pg_catalog."default",
    "UserDataField6", text COLLATE pg_catalog."default",
    "PlatformDesc", text COLLATE pg_catalog."default",
    "LicenseAgreeType", text COLLATE pg_catalog."default"
);



CREATE TABLE bridge.tbl_ibm_swcm_license_staging
( 
    "LicenseId" text,
    "LicenseOrderCountryCode" text,
    "CountryCodeDesc" text,
    "CustomerNumber" text,
    "LicenseName" text,
    "SwProductName" text,
    "LicenseVersionNumberVer" text,
    "LicenseVersionNumberRel" text,
    "LicenseVersionNumMod" text,
    "SwManufactName" text,
    "LicenseSherlokSkuNumber" text,
    "LicenseSherlokSkuName" text,
    "LicenseSwVersUpgrade" text,
    "LicenseOwnedByIbm" text,
    "LicenseSysplexPricing" text,
    "SupplierName" text,
    "LicenseTypeCode" text,
    "LicenseTypeDesc" text,
    "CapTypeDesc" text,
    "LicenseCost" text,
    "LicenseCostCurrCode" text,
    "LicensePoolUsable" text,
    "LicenseQuantity" text,
    "LicenseSkuCapacity" text,
    "LicenseTotalEntitledCapacity" text,
    "LicensePerpetual" text,
    "LicenseCreated" text,
    "LicenseStartDate" text,
    "LicenseEndDate" text,
    "LicenseRestrictedUse" text,
    "LicenseReusable" text,
    "LicenseSerialNumber" text,
    "LicenseComment" text,
    "LicenseStatusCode" text,
    "LicenseStatusDesc" text,
    "LicenseIbmContrRef" text,
    "LicenseDonglePhysKey" text,
    "LicensePurOrderNumber" text,
    "LicensePurOrderDate" text,
    "LicenseRestriction" text,
    "OSTypeCode" text,
    "OSTypeDesc" text,
    "MinorCode" text,
    "MinorCodeDesc" text,
    "UserDataField1" text,
    "UserDataField2" text,
    "UserDataField3" text,
    "UserDataField4" text,
    "UserDataField5" text,
    "UserDataField6" text,
    "PlatformDesc" text,
    "LicenseAgreeType" text
);